name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main # ou master, selon ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${DOCKER_USERNAME}/greenroots-front:$GITHUB_SHA .
          docker push ${DOCKER_USERNAME}/greenroots-front:$GITHUB_SHA

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} deploy@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
            cd /home/deploy/greenroots
            docker pull ${DOCKER_USERNAME}/greenroots-front:$GITHUB_SHA
            docker-compose down
            docker-compose up -d
          EOF
