name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main # ou master, selon ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Copy cert files
      #   run: |
      #     cp -r./certbot/conf/live/planttreeswith.me./certbot/conf/live/planttreeswith.me

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Vérifier le contenu du répertoire
        run: ls -la # Debug: Voir les fichiers présents

      - name: Build and push Docker image
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"  # Debug
          docker build -t ${{ secrets.DOCKER_USERNAME }}/greenroots-front:$GITHUB_SHA -f ./Dockerfile.cli .
          docker push ${{ secrets.DOCKER_USERNAME }}/greenroots-front:$GITHUB_SHA

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} deploy@${{ secrets.DIGITALOCEAN_IP }} << 'EOF'
            cd /home/deploy/greenroots
            docker pull ${{ secrets.DOCKER_USERNAME }}/greenroots-front:$GITHUB_SHA
            docker-compose down
            docker-compose up -d
          EOF
