name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main # ou master, selon ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Copy cert files
      #   run: |
      #     cp -r./certbot/conf/live/planttreeswith.me./certbot/conf/live/planttreeswith.me

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Vérifier le contenu du répertoire
        run: ls -la # Debug: Voir les fichiers présents

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"  # Debug
          docker build -t ${{ secrets.DOCKER_USERNAME }}/greenroots-client:$GITHUB_SHA -f ./Dockerfile.cli .
          docker push ${{ secrets.DOCKER_USERNAME }}/greenroots-client:$GITHUB_SHA

      # - name: Setup SSH Key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
      #     chmod 600 ~/.ssh/id_ed25519
      #     eval "$(ssh-agent -s)"
      #     ssh-add ~/.ssh/id_ed25519

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.DIGITALOCEAN_IP }} << EOF

            cd /home/deploy/greenroots
            sudo docker image pull ${{ secrets.DOCKER_USERNAME }}/greenroots-client:$GITHUB_SHA
            sudo docker compose down
            sudo docker compose up -d
          EOF
