name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main # ou master, selon ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Copy cert files
      #   run: |
      #     cp -r./certbot/conf/live/planttreeswith.me./certbot/conf/live/planttreeswith.me

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Vérifier le contenu du répertoire
        run: ls -la # Debug: Voir les fichiers présents

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"  # Debug
          docker build -t ${{ secrets.DOCKER_USERNAME }}/greenroots-client:$GITHUB_SHA -f ./Dockerfile.cli .
          docker push ${{ secrets.DOCKER_USERNAME }}/greenroots-client:$GITHUB_SHA

      - name: Debug private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 10

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass

      - name: Test SSH Connection
        run: |
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.DIGITALOCEAN_IP }} "echo 'SSH connection successful!'"

      - name: Deploy to DigitalOcean
        run: |
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.DIGITALOCEAN_IP }} <<EOF
            cd /home/deploy/greenroots
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker image pull ${{ secrets.DOCKER_USERNAME }}/greenroots-client:$GITHUB_SHA
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S rm -rf /etc/update-motd.d/99-one-click
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker-compose down
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S docker-compose up -d
          EOF
